name: pay_with_mona
description: "Flutter SDK for integrating the Mona payment gateway"
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  biometric_signature: ^6.2.0
  device_info_plus: ^11.3.0
  flutter_custom_tabs: ^2.4.0
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17
  intl: ^0.20.2
  local_auth: ^2.3.0
  local_auth_signature: ^1.0.12
  crypto: ^3.0.6
  otp_pin_field: ^1.4.1
  convert: ^3.1.2
  encrypt: ^5.0.3
  basic_utils: ^5.7.0
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/icons/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Neue Montreal
      fonts:
        - asset: assets/fonts/NeueMontreal-Regular.otf
