name: pay_with_mona
description: "Flutter SDK for integrating the Mona payment gateway"
version: 0.0.1

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  biometric_signature: ^6.2.0
  crypto: ^3.0.6
  device_info_plus: ^11.3.0
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_custom_tabs: ^2.1.0
  # flutter_passkey: ^1.0.5
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17
  http: ^1.3.0 # for firebase server-sent events (SSE)
  local_auth: ^2.3.0
  local_auth_signature: ^1.0.12
  package_info_plus: ^8.1.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: General Sans
      fonts:
        - asset: assets/fonts/GeneralSans-Light.otf
          weight: 300
        - asset: assets/fonts/GeneralSans-Regular.otf
          weight: 400
        - asset: assets/fonts/GeneralSans-Medium.otf
          weight: 500
        - asset: assets/fonts/GeneralSans-SemiBold.otf
          weight: 600
        - asset: assets/fonts/GeneralSans-Bold.otf
          weight: 700
        - asset: assets/fonts/GeneralSans-Bold.otf
          weight: 800
