name: pay_with_mona
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  crypto: ^3.0.6
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_custom_tabs: ^2.1.0
  flutter_svg: ^2.0.17
  http: ^1.3.0 # for firebase server-side events (SSE)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:

  assets:
    - assets/icons/
    - assets/fonts/
  
  fonts:
    - family: General Sans
      fonts:
        - asset: assets/fonts/GeneralSans-Light.otf
          weight: 300
        - asset: assets/fonts/GeneralSans-Regular.otf
          weight: 400
        - asset: assets/fonts/GeneralSans-Medium.otf
          weight: 500
        - asset: assets/fonts/GeneralSans-SemiBold.otf
          weight: 600
        - asset: assets/fonts/GeneralSans-Bold.otf
          weight: 700
        - asset: assets/fonts/GeneralSans-Bold.otf
          weight: 800
